# Generated by Django 4.1.2 on 2022-10-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emailContent', models.CharField(max_length=200)),
            ],
        ),
    ]
