# Generated by Django 4.1.2 on 2022-10-10 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_unity'),
    ]

    operations = [
        migrations.AddField(
            model_name='unity',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 10, 17, 15, 44, 269553)),
        ),
    ]
