# Generated by Django 4.1.2 on 2022-10-11 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_unity_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unity',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 11, 11, 13, 22, 145505)),
        ),
        migrations.AlterField(
            model_name='unity',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
